### ISSUE TITLE
Error conection

### ISSUE THREAD

**Issue by yashiroiori** [Edujugon/laradoo#1]
The error connection say this:

ErrorException in Odoo.php line 650:
Argument 1 passed to Edujugon\Laradoo\Odoo::setApiEndPoint() must be an instance of Edujugon\Laradoo\string, string given, called in Z:\PortableApps\xampp\htdocs\sitios\instrutek\erp\vendor\edujugon\laradoo\src\Odoo.php on line 318 and defined

**Comment by Edujugon** [comment]
Could you paste here how you are using the package to get that error?
I assume you are trying to get the Odoo version, but I need the full snippet in order to reproduce the error.

**Comment by Edujugon** [comment]
Also, let me know what PHP version you are using.

**Comment by yashiroiori** [comment]
Laravel 5.1
PHP 5.5

Yeah, I test with get version
$odoo = new \Edujugon\Laradoo\Odoo();
$version = $odoo->version();

Try to get partner:
$ids = $odoo->where('customer', '=', true)
            ->search('res.partner');

**Comment by Edujugon** [comment]
For now it only works from PHP 7.0 and above.
You should update your php version in order to make it work properly.

PS: I'm working on making it compatible with some minor versions.

**Comment by yashiroiori** [comment]
Ok let me try in hosting with PHP 7

**Comment by Edujugon** [comment]
Hi @yashiroiori ,

Did that work for you?

**Comment by yashiroiori** [comment]
Say same error:

ErrorException in Odoo.php line 650:
Argument 1 passed to Edujugon\Laradoo\Odoo::setApiEndPoint() must be an instance of Edujugon\Laradoo\string, string given, called in Z:\PortableApps\xampp\htdocs\sitios\instrutek\erp\vendor\edujugon\laradoo\src\Odoo.php on line 318 and defined

**Comment by Edujugon** [comment]
@yashiroiori 
What changes did you do?
Have you upgraded the php version to 7 or you are using the php5.5 branch of the package?

**Comment by yashiroiori** [comment]
\>composer require edujugon/larado:dev-php5.5
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package edujugon/larado could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Edujugon** [comment]
@yashiroiori ,
It should be like follows:
```
composer require edujugon/laradoo:dev-php5.5
```

There was a typo in the package name..

**Comment by yashiroiori** [comment]
Package installed, but return an error:

ErrorException in ripcord_client.php line 485:
Undefined variable: http_response_header

**Comment by Edujugon** [comment]
@yashiroiori ,

That's weird. This is a php magic variable and should be available for you..
Try to find your php.ini and uncomment allow_url_fopen = On or change it to On if it's Off.

Anyway, I would recommend you to upgrade to php 7 since it comes with a lot of improvements..

**Comment by yashiroiori** [comment]
Excellent.
Let me finish a tree view from stock of odoo to try again.

**Comment by garauz23** [comment]
Im getting the same error: 

Undefined variable: http_response_header

I'm using Ubuntu 16, Php 7.0.22

**Comment by Edujugon** [comment]
What package version are you running?

**Comment by garauz23** [comment]
this is the error i get:
ErrorException in ripcord_client.php line 485: 
Undefined variable: http_response_header

**Comment by Edujugon** [comment]
Is there any repo I can check?
I'll try to reproduce the problem.

**Comment by Edujugon** [comment]
Hi @garauz23 ,

Could you solve the issue? 
I've set up a new Laravel 5.2 project and tested the package and It works fine.

You can share the repo with me so that I can do further test.

**Comment by activeyossi** [comment]
I am getting the same error, but I think this issue is actually generated from a @file_get_contents error.
From what I have been reading $http_response_header variable is created after a successful file_get_contents. so If we have an error, $http_response_header is not created globally by PHP and it throws an error before getting to the if `( !$result )` check
I changed the code to:

`		$result  = @file_get_contents( $url, false, $context );

		if ( !$result )
		{
			throw new Ripcord_TransportException( 'Could not access ' . $url, 
				ripcord::cannotAccessURL );
		}
		else {
            $this->responseHeaders = $http_response_header;
        }
        return $result;
	}`
and now the error is showing actually as:

` [Ripcord_TransportException]                         
  Could not access ****.odoo.com/xmlrpc/2/common  ` 

In my case, it's probably a credentials issue, which hopefully I'll figure out shortly.

What is the proper way to set the credentials if you are using odoo web ver 10?

Thanks
Joe

**Comment by activeyossi** [comment]
Figure it out....
I didn't put the full URL for the host...
host name must be "https//companydb.odoo.com"

**Comment by guberakannan** [comment]
Hey Guys I got the same issue.. after digging in, I came to solve this by adding one more vendor package - DarkaOnLine
https://github.com/DarkaOnLine/Ripcord  
This solved the error.
Now $odoo->version gives following output -

{"server_serie":"11.0",
"server_version_info":[11,0,0,"final",0,""],
"server_version":"11.0",
"protocol_version":1}

Cheers :+1:
