### ISSUE TITLE
 (1/1) ErrorException Undefined variable: http_response_header

### ISSUE THREAD

**Issue by hafizSiddiq7675** [Edujugon/laradoo#11]
I am having the subject issue with PHP version 7.1, Please Let me Know How to proceed as I have the following in laradoo.php configuration file

<?php
return [
    'api-suffix' => 'xmlrpc',     // 'xmlrpc' from version 7.0 and earlier, 'xmlrpc/2' from version 8.0 and above.

    //Credentials
    'host'       => 'http://myhost.com:8029',
    'db'         => 'dbname',
    'username'   => 'username',
    'password'   => 'password',
];
It is working fine on my local computer but when I deploy application on server this issue arises.

**Comment by Edujugon** [comment]
Hi @hafizSiddiq7675 ,
Make sure your host credential is correctly set, including https if it's under ssl.

**Comment by Edujugon** [comment]
It seems to be something related to your production environment since you said it's working fine on local..

Could you provide more details?

**Comment by hafizSiddiq7675** [comment]
What details please tell me so that I can look into this.

**Comment by Edujugon** [comment]
Please check the network settings on your server, also check if you have access to the host you're using from your server.

I would also google the issue since it is not related to this package and I can not reproduce it from my end..

**Comment by hafizSiddiq7675** [comment]
It is working now!
Thanks for such an amazing liberary.

**Comment by mgarcia96** [comment]
Hey! Same here.
It works fine in TINKER but not in Postman or Browser
