### ISSUE TITLE
   Ripcord_ConfigurationException  : PHP XMLRPC library is not installed

### ISSUE THREAD

**Issue by alfredlaggner** [Edujugon/laradoo#12]

**Comment by alfredlaggner** [comment]
I moved my laravel package to a faster server by copying the project folder to that new server (setup with laravel forge on didgial ocean). Now when I try get data fro odoo I get this error:

**Comment by Wididou** [comment]
I had the same issue I would like to know how did you fix this please ?

**Comment by JaoAustero** [comment]
@Wididou did you solve this issue? I do have the same issue.

**Comment by Wididou** [comment]
@JaoAustero Yes I did resolve it, well I had a problem with my connection with the Postgres database of Odoo, as soon as I fixed it & installed Odoo appropriately, then entered the right credentials (db_name, user_name & password) it worked fine for me.

**Comment by JaoAustero** [comment]
@Wididou what is the solution for xmlrpc? what did you do? can you share here?

**Comment by JaoAustero** [comment]
If you are having problem with **XMLRPC** you need to install this module based on the php version that you have, you need to specify the version if you have multiple version in your local or virtual box, Here is the link below.

[https://jsnelders.com/Blog/1036/install-xml-rpc-for-php-7-2-on-ubuntu-linux/](PHP Module)

**Comment by aroldos91** [comment]
![Screenshot_2020-08-11 Screenshot](https://user-images.githubusercontent.com/61445551/89956261-d2a07d80-dc02-11ea-999d-b3bc1c96c7bb.png)
How can I fix it, Laravel 7, Php 7.2, XAMPP local server, CPanel remote server
