### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by yashiroiori** [Edujugon/laradoo#19]
Hi good job.
I'm making a connector with Laravel 6 to take products from odoo, but in some case the server is down, how can make with Laravel request send a ping to odoo server and validate is online??

**Comment by Edujugon** [comment]
Hey @yashiroiori ,

There is not ping method in the package but you may try with any of the following methods:

```
// If not logged in
$version = $odoo->version();

// Once you're logged in
$userId= $this->odoo->getUid();
or
$can = $odoo->can('read', 'res.partner');
```

Although they are not meant for ping purposes, they are the lighter actions and you could achieve what you need.

**Comment by yashiroiori** [comment]
> Hey @yashiroiori ,
> 
> There is not ping method in the package but you may try with any of the following methods:
> 
> ```
> // If not logged in
> $version = $odoo->version();
> 
> // Once you're logged in
> $userId= $this->odoo->getUid();
> or
> $can = $odoo->can('read', 'res.partner');
> ```
> 
> Although they are not meant for ping purposes, they are the lighter actions and you could achieve what you need.

Tankh you very much
