### ISSUE TITLE
Switch Companies.

### ISSUE THREAD

**Issue by andyslater99** [Edujugon/laradoo#2]
Hi @Edujugon ,

Is it possible to switch companies in the get request to Odoo via the package?, e.g. If there are multiple companies in the Odoo instance, but we only wanted to get/put/delete data from company id 4? Is this viable?

Andy

**Comment by Edujugon** [comment]
Hi @andyslater99 ,
Sorry for my delay in reply..

I never tried that. have you tried with "where" method looking for that company id?
