### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by johannoscar** [Edujugon/laradoo#24]
Error upgrading from Laravel 6 to 7.
Problem 1
    - Conclusion: remove edujugon/laradoo 2.1.0
    - Conclusion: don't install edujugon/laradoo 2.1.0

**Comment by Edujugon** [comment]
Hey @johannoscar ,

I'll try to get same time tomorrow to make the package compatible with L7.

I'll post an update here when it's done.

**Comment by johannoscar** [comment]
Thank you @Edujugon !

**Comment by Edujugon** [comment]
Hey @johannoscar ,
I've just published a new release (v2.2.0) with L7 support.

Let me know if that worked for you.

**Comment by johannoscar** [comment]
Eduardo. Many thanks. It worked perfect!

**Comment by Edujugon** [comment]
Glad it worked!
