### ISSUE TITLE
Undefined variable: http_response_header

### ISSUE THREAD

**Issue by yashiroiori** [Edujugon/laradoo#4]
This work on php 7.2??
Odoo versión: 8
In this case sendme an error in line 485 from edujugon/laradoo/src/ripcord/ripcord_client.php

$this->responseHeaders = $http_response_header;

Thanks.

**Comment by Edujugon** [comment]
Hi @yashiroiori ,
That variable should be available in php 7. Could you paste the exact error message you get?

**Comment by Edujugon** [comment]
Closing this since there is no update from the issue creator.

Feel free to reopen it if necessary.

**Comment by raakesh** [comment]
@yashiroiori I had the problem as well. To fix this issue you have to use the host with `http://`.
**Example:**
```php
return [
    'api-suffix' => 'xmlrpc/2',     // 'xmlrpc' from version 7.0 and earlier, 'xmlrpc/2' from version 8.0 and above.

    //Credentials
    'host'       => 'http://example.com',
    'db'         => 'dbname',
    'username'   => 'username',
    'password'   => 'password',
];
```

**Comment by kurodaSensei** [comment]
Greetings, I present the same problem, in my case I am using Lumen 5.8 on Nginx, PHP7.2, S.O Linux.

In my case I receive the following error message:

`
ErrorException
--
Undefined variable: http_response_header
--
in ripcord_client.php line 485
`
In error body
`
variable: http_response_header', 
'/home/kuroda/Sites/odoo-webservices/vendor/edujugon/laradoo/src/ripcord/ripcord_client.php', 
485, array(
  'url' => 'https://my-host.com/xmlrpc/common', 
  'request' => '<?xml version="1.0" encoding="utf-8"?>
    <methodCall>
    <methodName>version</methodName>
    <params/>
    </methodCall>', 
    'options' => array(
      'http' => array(
        'method' => 'POST', 
        'header' => 
        'Content-Type: text/xml', 
        'content' => '<?xml version="1.0" encoding="utf-8"?><methodCall><methodName>version</methodName><params/></methodCall>'
      )
    ), 
  'context' => resource, 
  'result' => false)
  )
`

**Comment by kurodaSensei** [comment]
Any idea for this problem?

**Comment by raakesh** [comment]
@kurodaSensei share your laradoo.php config file.

**Comment by 10xnorellana** [comment]
same issue @kurodaSensei 

return [
    'api-suffix' => 'xmlrpc/2',     // 'xmlrpc' from version 7.0 and earlier, 'xmlrpc/2' from version 8.0 and above.

    //Credentials
    'host'       => 'http://example.com',
    'db'         => 'dbname',
    'username'   => 'username',
    'password'   => 'password',
];

**Comment by kurodaSensei** [comment]
Sorry for later, I solved my problem, this error be caused of a error in a variable.
