### ISSUE TITLE
How to authenticate users from res.users model

### ISSUE THREAD

**Issue by divyeshjesadiya** [Edujugon/laradoo#41]
After connection, I want to authenticate users from res.users model. I have tried this but not had any success.

`$odoo = new \Edujugon\Laradoo\Odoo();

        $odoo = $odoo->connect();

        $password = "12345";
        $iterations = 1000;

        // Generate a random IV using openssl_random_pseudo_bytes()
        // random_bytes() or another suitable source of randomness
        $salt = openssl_random_pseudo_bytes(16);

        $hash = hash_pbkdf2("sha512", $password, $salt, $iterations, 20);

        $models = $odoo->where('login', 'test@test.com')->where('password', $hash)->fields('name','login','password')->get('res.users');`

**Comment by yaziderman** [comment]
@divyeshjesadiya  Were you trying to implement a single sign on? or other purposes?

**Comment by divyeshjesadiya** [comment]
@yaziderman At that time I had an understanding of connection and authentication were two different things in the package but after a while, I understood that connection and authentication are the same in the package. So, this is not an issue. we can close this issue.
