### ISSUE TITLE
Store many2many or one2many attribute

### ISSUE THREAD

**Issue by hamihaa** [Edujugon/laradoo#6]
First, thank you for this great library, it's well documented and easy to use.

Only thing that I can't figure out is how to properly create many2many or one2many  relationship on a model. 

An example: 
I have a custom model named Item, that is already populated with items.
Then i create another model named Order, that has these attributes: ['customer_id', 'order_type', 'item_ids'].

request would be like this:
```
    ->create('custom_db.order', [ 'customer_id' => 'name', 'order_type' => 0, 'item_ids' => [1, 2, 3]]
```
Order gets stored in Odoo with correct customer data and order type, but 'item_ids' is empty every time. I've also tried following the Odoo documentation (https://www.odoo.com/documentation/11.0/reference/orm.html#odoo.models.Model.write )
with these examples, but no luck:

 "item_ids" => [4, [1, 2, 3], 0] or "item_ids" => [0, 0, [1, 2, 3]]

thank you for your help.

**Comment by hamihaa** [comment]
Figured it out, i was missing an extra array wrapper and calling wrong code function.
Correct way for creating an array:

```
'item_ids' => [[6, false, [1, 2, 3]]]
```

**Comment by Edujugon** [comment]
Happy you figured it out :)

Let me know if you face any further issue..
