### ISSUE TITLE
one2many, many2many and selection fields examples

### ISSUE THREAD

**Issue by dnsimmons** [Edujugon/laradoo#7]
Could you please provide a simple example in the readme of the usage for dealing with Odoo's one2many, many2many and selection fields? Particularly how one would use them with create() and update(). In Python, it seems as if these are dealt with using special tuple commands however for PHP documentation seems very hard to find for these types of things and it would be extremely helpful.

For illustrative purposes in my particular project, I haven't been able to figure out how to relate a CRM lead tag to a lead during the creation process using Laradoo:

        $id = $odoo->create('crm.lead', [
            'type'          => 'lead',
            'priority'      => 0, <-- what do we pass here for this selection field?
            'name'          => 'Example',
            'contact_name'  => 'John Doe',
            'phone'         => '555-555-5555',
            'email_from'    => 'example@domain.com',
            'description'   => 'Just some text.',
            'tag_ids'       => [1], <-- What do we pass here for this one2many field?
        ]);

In the example above when trying to set the priority selection field to an int other than 0  fails and when trying to pass an array of tag_ids (1 is valid tag id in my project) the lead remains untagged.

**Comment by Edujugon** [comment]
Hi @dnsimmons ,

Have you tried to add an extra array wrapper?
Something like:

`'tag_ids'       => [[1]]`

**Comment by dnsimmons** [comment]
@Edujugon

Thank you for the quick reply.

I actually did try that before opening the issue. 
Odoo returns a "list index out of range" when using:

'tag_ids'       => [[1]]

I have also tried imitating Pythons tuples (produces same error):

'tag_ids' => [0,0, [1]]

And also just an integer which of course returns a not-iterable error:

'tag_ids' => 1

**Comment by dnsimmons** [comment]
@Edujugon

Using this documentation: https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L3020-L3055

After some fiddling around I managed to replicate the way the command tuples work:

'tag_ids' => [4, [1]]

Where 4 is the command identifier to add a new relation and 1 is the id of the tag.

I still believe some examples would be in order in Laradoos readme for these types of test cases.

**Comment by Edujugon** [comment]
Hey @dnsimmons ,

Happy to know you made it work. :)

I agree, the documentation should expose some examples on that topic. If you're up to create a PR adding those examples in readme file, that would be more than welcome! otherwise I will add them as soon as  I can.
